application:
  port: 8000
database:
  port: 5432
  database_name: "farms"
email_client:
  base_url: "localhost"
  sender_email: "test@farms.com"
  authorization_token: ""
  timeout_milliseconds: 10000