application:
  port: 8000
database:
  max_connections: 100 # default
  timeout_seconds: 5
  port: 5432
  database_name: "farms"
idempotency:
  engine: "redis"
  ttl_seconds: 600 # 10 min
  redis_key_prefix: "idem"
redis:
  pool_max_size: 20
  timeout_seconds: 5
  session_key_prefix: "sess"
email_client:
  base_url: "localhost"
  sender_email: "test@farms.com"
  authorization_token: ""
  timeout_milliseconds: 10000